### ISSUE TITLE
.net core & more compatible version published to nuget

### ISSUE THREAD

**Issue by apawsey** [ninety7/DbContextScope.EF7#2]
Hi,

I published a new version of the dbcontextscope stuff which is compatible with both .net 4+ and .net standard 1.3+ to nuget today.  I gave you credit as I looked at some of your code regarding the changes that made it compatible for ef core, and included some of it, although I ended up disabling it instead of throwing an exception as you did.

Current package works with ef6 for .net 4+ and efcore for .net standard... It seems though you're using efcore on .net 4.5.  I think I'll need to split the package for ef6 and efcore separately.

Any comments are welcomed!

**Comment by ninety7** [comment]
Thanks a lot for that. Good to know that this project is alive.
